spring.application.name=tripping.app

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tripping}
spring.datasource.username=${DB_USUARIO:postgres}
spring.datasource.password=${DB_SENHA:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

aplicacao.cors.origem-permitida=${CORS_ORIGEM_PERMITIDA:http://localhost:5173}
